# Generated by Django 5.0.2 on 2026-04-12 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0014_remove_signup_id_signup_mobileno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=40, unique=True)),
                ('address_text', models.CharField(default='', max_length=250)),
                ('city', models.CharField(default='', max_length=70)),
                ('country', models.CharField(default='', max_length=70)),
                ('postcode', models.CharField(default='', max_length=20)),
                ('total_try_items', models.IntegerField(default=0)),
                ('reference_value', models.IntegerField(default=0)),
                ('try_fee', models.IntegerField(default=0)),
                ('is_first_order', models.BooleanField(default=False)),
                ('try_payment_mode', models.CharField(default='free', max_length=20)),
                ('try_payment_status', models.CharField(default='paid', max_length=20)),
                ('status', models.CharField(default='Try Requested', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobileno', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FinalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=40, unique=True)),
                ('selected_items_count', models.IntegerField(default=0)),
                ('items_total', models.IntegerField(default=0)),
                ('wallet_credit', models.IntegerField(default=0)),
                ('final_payable', models.IntegerField(default=0)),
                ('payment_mode', models.CharField(default='upi', max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('status', models.CharField(default='ready_for_payment', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('try_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.tryorder')),
            ],
        ),
        migrations.CreateModel(
            name='TryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=120)),
                ('brand_name', models.CharField(default='', max_length=120)),
                ('qty', models.IntegerField(default=1)),
                ('unit_price', models.IntegerField(default=0)),
                ('line_total', models.IntegerField(default=0)),
                ('product_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sevenshadesapp.productdetails')),
                ('try_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.tryorder')),
            ],
        ),
        migrations.CreateModel(
            name='FinalOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=120)),
                ('brand_name', models.CharField(default='', max_length=120)),
                ('qty', models.IntegerField(default=1)),
                ('unit_price', models.IntegerField(default=0)),
                ('line_total', models.IntegerField(default=0)),
                ('final_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.finalorder')),
                ('try_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sevenshadesapp.tryorderitem')),
            ],
        ),
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobileno', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
