# Generated by Django 5.0.2 on 2026-04-12 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0015_tryorder_finalorder_tryorderitem_finalorderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(default='', max_length=120)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(default='', max_length=120)),
                ('bike_number', models.CharField(default='', max_length=40)),
                ('zone', models.CharField(default='', max_length=70)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(default='Assigned', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('try_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.tryorder')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.deliveryrider')),
            ],
        ),
    ]
