# Generated by Django 5.0.2 on 2026-09-20 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0016_deliveryrider_deliveryassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tryorder',
            name='address_type',
            field=models.CharField(default='Residential', max_length=30),
        ),
        migrations.AddField(
            model_name='tryorder',
            name='delivery_mode',
            field=models.CharField(default='standard', max_length=30),
        ),
        migrations.AddField(
            model_name='tryorder',
            name='delivery_slot',
            field=models.CharField(default='10 AM - 2 PM', max_length=50),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(default='Residential', max_length=30),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mobile', models.CharField(max_length=15)),
                ('user_name', models.CharField(default='Customer', max_length=70)),
                ('rating', models.IntegerField(default=5)),
                ('review_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.productdetails')),
            ],
        ),
    ]
