# Generated by Django 4.2.30 on 2026-09-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0017_productdetails_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='trial_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='trial_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
