# Generated by Django 4.2.30 on 2026-09-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0019_deliverybatch_deliveryassignment_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamperProofTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=40, unique=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('final_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.finalorderitem')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hygiene_status', models.CharField(default='Pending', max_length=30)),
                ('condition', models.CharField(default='Good', max_length=30)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('final_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.finalorderitem')),
            ],
        ),
    ]
