# Generated by Django 4.2.30 on 2026-09-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0020_tamperprooftag_returneditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=70, unique=True)),
                ('postcodes', models.TextField(help_text='Comma-separated postcodes')),
            ],
        ),
        migrations.CreateModel(
            name='ExcludedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=70, unique=True)),
                ('postcode', models.CharField(max_length=20)),
            ],
        ),
    ]
