# Generated by Django 4.2.30 on 2026-09-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0021_deliveryzone_excludedarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryorder',
            name='assigned_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sevenshadesapp.deliveryrider'),
        ),
        migrations.AddField(
            model_name='tryorder',
            name='final_bill',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tryorder',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL_TRIAL_FEE', 'Partial Trial Fee'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='tryorder',
            name='trial_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tryorder',
            name='trial_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('SOS', 'SOS')], default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='tryorderitem',
            name='status',
            field=models.CharField(choices=[('TRY_REQUESTED', 'Try Requested'), ('PURCHASED', 'Purchased'), ('RETURNED', 'Returned')], default='TRY_REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='tryorder',
            name='status',
            field=models.CharField(choices=[('TRY_REQUESTED', 'Try Requested'), ('ASSIGNED', 'Assigned'), ('OUT_FOR_TRIAL', 'Out for Trial'), ('TRIAL_IN_PROGRESS', 'Trial in Progress'), ('SELECTION_SUBMITTED', 'Selection Submitted'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='TRY_REQUESTED', max_length=60),
        ),
    ]
