# Generated by Django 5.0.2 on 2026-09-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0023_hash_account_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorderitem',
            name='color',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='finalorderitem',
            name='size',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='tryorderitem',
            name='color',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='tryorderitem',
            name='size',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='tryorderitem',
            name='stock_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
