# Generated by Django 5.0.2 on 2026-09-23 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0024_checkout_variant_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Damaged', 'Damaged')], max_length=20)),
                ('status', models.CharField(choices=[('Collected', 'Collected'), ('Received', 'Received'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Collected', max_length=20)),
                ('recorded_by', models.CharField(max_length=100)),
                ('received_by', models.CharField(blank=True, default='', max_length=100)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trial_return', to='sevenshadesapp.tryorderitem')),
            ],
        ),
    ]
