# Generated by Django 5.0.2 on 2026-09-23 19:47

from django.db import migrations, models


def normalize_delivery(apps, schema_editor):
    from django.db.models import Count
    Assignment = apps.get_model('sevenshadesapp', 'DeliveryAssignment')
    Order = apps.get_model('sevenshadesapp', 'TryOrder')
    duplicates = Assignment.objects.values('try_order_id').annotate(n=Count('id')).filter(n__gt=1)
    if duplicates.exists():
        raise RuntimeError('Duplicate delivery assignments require manual reconciliation before this migration. No records were deleted.')
    aliases = {'Try Requested': 'TRY_REQUESTED', 'Assigned': 'ASSIGNED', 'On Route': 'OUT_FOR_TRIAL',
        'Trial In Progress': 'TRIAL_IN_PROGRESS', 'Trial Completed': 'SELECTION_SUBMITTED',
        'Trial Completed - No Purchase': 'NO_PURCHASE', 'Completed - No Purchase': 'NO_PURCHASE',
        'Completed': 'DELIVERED', 'Final Payment Pending': 'PAYMENT_PENDING'}
    for old, new in aliases.items():
        Order.objects.filter(status=old).update(status=new)
    for old, new in {'ASSIGNED': 'Assigned', 'Assigned (SOS)': 'Assigned', 'OUT_FOR_TRIAL': 'On Route',
        'TRIAL_IN_PROGRESS': 'Trial In Progress', 'Trial Started': 'Trial In Progress', 'Trial Ended': 'Trial In Progress', 'DELIVERED': 'Delivered'}.items():
        Assignment.objects.filter(status=old).update(status=new)
    for assignment in Assignment.objects.select_related('try_order'):
        order = assignment.try_order
        order.assigned_rider_id = assignment.rider_id
        if order.status == 'TRY_REQUESTED':
            order.status = {'Assigned': 'ASSIGNED', 'On Route': 'OUT_FOR_TRIAL', 'Trial In Progress': 'TRIAL_IN_PROGRESS'}.get(assignment.status, order.status)
        order.save(update_fields=['assigned_rider', 'status'])


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0025_trial_return_workflow'),
    ]

    operations = [
        migrations.RunPython(normalize_delivery, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tryorder',
            name='status',
            field=models.CharField(choices=[('TRY_REQUESTED', 'Try Requested'), ('ASSIGNED', 'Assigned'), ('OUT_FOR_TRIAL', 'Out for Trial'), ('TRIAL_IN_PROGRESS', 'Trial in Progress'), ('SELECTION_SUBMITTED', 'Selection Submitted'), ('DELIVERED', 'Delivered'), ('PAYMENT_PENDING', 'Payment Pending'), ('NO_PURCHASE', 'Trial Completed - No Purchase'), ('CANCELLED', 'Cancelled')], default='TRY_REQUESTED', max_length=60),
        ),
        migrations.AddConstraint(
            model_name='deliveryassignment',
            constraint=models.UniqueConstraint(fields=('try_order',), name='one_assignment_per_trial'),
        ),
    ]
