# Generated by Django 5.0.2 on 2026-09-23 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0026_delivery_consistency'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='approved_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='bill_revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='cash_collected_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trialreturn',
            name='steam_pressed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trialreturn',
            name='steam_pressed_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trialreturn',
            name='tag_intact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tryorder',
            name='status',
            field=models.CharField(choices=[('TRY_REQUESTED', 'Try Requested'), ('ASSIGNED', 'Assigned'), ('OUT_FOR_TRIAL', 'Out for Trial'), ('TRIAL_IN_PROGRESS', 'Trial in Progress'), ('SELECTION_SUBMITTED', 'Selection Submitted'), ('DELIVERED', 'Delivered'), ('AWAITING_TRIAL_PAYMENT', 'Awaiting Trial Fee'), ('PAYMENT_PENDING', 'Payment Pending'), ('NO_PURCHASE', 'Trial Completed - No Purchase'), ('CANCELLED', 'Cancelled')], default='TRY_REQUESTED', max_length=60),
        ),
        migrations.CreateModel(
            name='GatewayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('trial', 'Trial fee'), ('final', 'Final purchase')], max_length=10)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('amount_paise', models.PositiveIntegerField()),
                ('gateway_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('state', models.CharField(default='CREATING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('try_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sevenshadesapp.tryorder')),
            ],
        ),
        migrations.CreateModel(
            name='OrderReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sevenshadesapp.finalorder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gatewaypayment',
            constraint=models.UniqueConstraint(fields=('try_order', 'purpose', 'revision'), name='one_payment_per_bill_revision'),
        ),
    ]
