# Generated by Django 5.0.2 on 2026-09-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0028_dispatch_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryorder',
            name='status',
            field=models.CharField(choices=[('TRY_REQUESTED', 'Try Requested'), ('ASSIGNED', 'Assigned'), ('OUT_FOR_TRIAL', 'Out for Trial'), ('TRIAL_IN_PROGRESS', 'Trial in Progress'), ('TRIAL_COMPLETED', 'Trial Completed'), ('AWAITING_SELECTION_APPROVAL', 'Awaiting Selection Approval'), ('SELECTION_SUBMITTED', 'Selection Submitted'), ('DELIVERED', 'Delivered'), ('AWAITING_TRIAL_PAYMENT', 'Awaiting Trial Fee'), ('PAYMENT_PENDING', 'Payment Pending'), ('NO_PURCHASE', 'Trial Completed - No Purchase'), ('CANCELLED', 'Cancelled')], default='TRY_REQUESTED', max_length=60),
        ),
    ]
