# Generated by Django 5.0.2 on 2026-09-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0029_trial_completed_selection_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.CharField(max_length=36, unique=True)),
                ('mobile', models.CharField(db_index=True, max_length=10)),
                ('purpose', models.CharField(max_length=10)),
                ('session_hash', models.CharField(max_length=64)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('code_hash', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
