# Generated by Django 5.0.2 on 2026-09-23 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0030_otp_challenges'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('status', models.CharField(default='Open', max_length=20)),
                ('priority', models.CharField(default='Normal', max_length=10)),
                ('response', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_by', models.CharField(blank=True, default='', max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sevenshadesapp.signup')),
            ],
        ),
    ]
