# Generated by Django 5.0.2 on 2026-09-23 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0031_support_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysubcategory',
            name='maincategoryid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sevenshadesapp.maincategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brandid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sevenshadesapp.brands'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maincategoryid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sevenshadesapp.maincategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategoryid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sevenshadesapp.mysubcategory'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='brandid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sevenshadesapp.brands'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='maincategoryid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sevenshadesapp.maincategory'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='productid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sevenshadesapp.product'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='subcategoryid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sevenshadesapp.mysubcategory'),
        ),
        migrations.AlterField(
            model_name='tryorderitem',
            name='product_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sevenshadesapp.productdetails'),
        ),
    ]
