# Generated by Django 5.0.2 on 2026-09-23 22:53

from django.db import migrations, models


def initialize_deadlines(apps, schema_editor):
    from datetime import timedelta
    Order = apps.get_model('sevenshadesapp', 'TryOrder')
    Assignment = apps.get_model('sevenshadesapp', 'DeliveryAssignment')
    for order in Order.objects.all().iterator():
        updates = {}
        if order.status == 'AWAITING_TRIAL_PAYMENT':
            updates['reservation_expires_at'] = order.created_at + timedelta(minutes=30)
        if order.status not in ('TRY_REQUESTED','AWAITING_TRIAL_PAYMENT','ASSIGNED','CANCELLED') or Assignment.objects.filter(try_order=order).exclude(status__in=['Assigned','Cancelled']).exists():
            updates['dispatched_at'] = order.updated_at
        if order.status == 'CANCELLED':
            updates['cancelled_at'] = order.updated_at
        if updates:
            Order.objects.filter(pk=order.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0032_protect_catalog_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaypayment',
            name='receipt_reference',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='gatewaypayment',
            name='recovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatewaypayment',
            name='recovered_by',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='tryorder',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tryorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tryorder',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tryorder',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(initialize_deadlines, migrations.RunPython.noop),
    ]
