# Generated by Django 5.0.2 on 2026-09-24 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0033_reservation_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sevenshadesapp.deliveryrider'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sevenshadesapp.signup'),
        ),
    ]
