# Generated by Django 5.0.2 on 2026-09-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0034_supportticket_rider_alter_supportticket_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryorder',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
