# Generated by Django 5.0.2 on 2026-09-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0035_tryorder_scheduled_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productdetails',
            constraint=models.CheckConstraint(check=models.Q(('qty__gte', 0)), name='product_details_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productdetails',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='product_details_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productdetails',
            constraint=models.CheckConstraint(check=models.Q(('offerprice__gte', 0)), name='product_details_offerprice_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productdetails',
            constraint=models.UniqueConstraint(fields=('productid', 'color', 'size'), name='unique_product_color_size'),
        ),
    ]
