# Generated by Django 5.0.2 on 2026-09-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0036_productdetails_product_details_qty_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialreturn',
            name='scanned_tag',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='trialreturn',
            name='tag_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tryorderitem',
            name='security_tag',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
