# Generated by Django 5.0.2 on 2026-09-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0037_trialreturn_scanned_tag_trialreturn_tag_verified_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(fields=('product_details', 'user_mobile'), name='unique_customer_product_review'),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='product_review_rating_1_to_5'),
        ),
    ]
