# Generated by Django 4.2.30 on 2026-09-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0040_revokedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price_tag', models.CharField(max_length=50)),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('tier_color', models.CharField(default='blue', max_length=20)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maincategoryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sevenshadesapp.maincategory')),
                ('subcategoryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sevenshadesapp.mysubcategory')),
            ],
        ),
    ]
