# Generated by Django 4.2.30 on 2026-09-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0042_purge_test_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PAGE_VIEW', 'Page View'), ('USER_EVENT', 'User Event')], default='USER_EVENT', max_length=20)),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('page_path', models.CharField(blank=True, default='', max_length=255)),
                ('page_title', models.CharField(blank=True, default='', max_length=255)),
                ('user_mobile', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('user_role', models.CharField(blank=True, default='anonymous', max_length=20)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_name', 'created_at'], name='sevenshades_event_n_fcc537_idx'), models.Index(fields=['event_type', 'created_at'], name='sevenshades_event_t_7a1a31_idx')],
            },
        ),
    ]
