# Generated by Django 5.2.17 on 2026-10-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0043_analyticsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
