# Generated by Django 4.2.30 on 2026-10-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0044_productdetails_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount')], default='percentage', max_length=20)),
                ('discount_value', models.FloatField(default=0.0)),
                ('max_discount', models.FloatField(blank=True, null=True)),
                ('min_order_amount', models.FloatField(default=0.0)),
                ('scope', models.CharField(choices=[('all', 'Entire Store / All Products'), ('category', 'Specific Categories'), ('subcategory', 'Specific Subcategories'), ('product', 'Specific Products')], default='all', max_length=20)),
                ('target_ids', models.JSONField(blank=True, default=list)),
                ('total_usage_limit', models.IntegerField(blank=True, null=True)),
                ('used_count', models.IntegerField(default=0)),
                ('per_user_limit', models.IntegerField(default=1)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, max_length=50)),
                ('order_id', models.CharField(blank=True, default='', max_length=50)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='sevenshadesapp.coupon')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
    ]
