"""
Django settings for sevenshades project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
import secrets

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Local key file is ignored by git. Production should use the environment variable.
_sms_key_file = BASE_DIR / '.fast2sms-key'
FAST2SMS_API_KEY = os.environ.get('FAST2SMS_API_KEY', '')
if not FAST2SMS_API_KEY and _sms_key_file.exists():
    FAST2SMS_API_KEY = _sms_key_file.read_text().strip()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set in production.')
    secret_path = BASE_DIR / '.local-secret'
    try:
        with secret_path.open('x') as secret_file:
            secret_file.write(secrets.token_urlsafe(64))
    except FileExistsError:
        pass
    SECRET_KEY = secret_path.read_text().strip()

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver').split(',')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'sevenshadesapp.apps.SevenshadesappConfig',
    'corsheaders',
]

ASGI_APPLICATION = 'sevenshades.asgi.application'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'sevenshadesapp.error_handling.SafeExceptionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOWED_ORIGINS = os.environ.get('FRONTEND_ORIGINS', 'http://127.0.0.1:3000,http://localhost:3000').split(',')
CORS_ALLOW_CREDENTIALS = True
CORS_URLS_REGEX = r'^/(api|media|static|payments)/.*$'
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_AGE = 8 * 60 * 60
ROOT_URLCONF = 'sevenshades.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sevenshades.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DB_ENGINE = os.environ.get('DB_ENGINE', '')
if DB_ENGINE:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.environ.get('DB_NAME', 'sevenshades'),
            'USER': os.environ.get('DB_USER', ''),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DB_PORT', '3306'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

# Media files — MEDIA_ROOT is set to BASE_DIR so that ImageField(upload_to='static/')
# resolves to BASE_DIR/static/, which is where all product/category/banner images are stored.
# secure_media_serve restricts access to image extensions only and blocks path traversal.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR

# Upload safety: non-executable file permissions and upload limits
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REDIS_URL = os.environ.get('REDIS_URL', '')

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'sevenshades-cache',
        }
    }
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# Configure locally; never put gateway secrets in frontend code.
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = os.environ.get('RAZORPAY_WEBHOOK_SECRET', '')
RECEIPT_SELLER_NAME = os.environ.get('RECEIPT_SELLER_NAME', 'SevenShades')
RECEIPT_SELLER_ADDRESS = os.environ.get('RECEIPT_SELLER_ADDRESS', '')

# Fixed OTP is explicitly limited to local debug mode. SMS integration is pending.
OTP_TEST_MODE = DEBUG and os.environ.get('OTP_TEST_MODE', '1') == '1'

SILENCED_SYSTEM_CHECKS = ['fields.E180']

RATE_LIMITS = {
    'AUTH': {
        'IP_MAX_REQUESTS': int(os.environ.get('RATE_LIMIT_AUTH_IP_MAX', 100)),
        'IP_WINDOW': int(os.environ.get('RATE_LIMIT_AUTH_IP_WINDOW', 60)),
        'ACCOUNT_MAX_ATTEMPTS': int(os.environ.get('RATE_LIMIT_AUTH_ACC_MAX', 10)),
        'ACCOUNT_WINDOW': int(os.environ.get('RATE_LIMIT_AUTH_ACC_WINDOW', 900)),
        'BACKOFF_BASE': float(os.environ.get('RATE_LIMIT_AUTH_BACKOFF_BASE', 2.0)),
        'BACKOFF_FACTOR': float(os.environ.get('RATE_LIMIT_AUTH_BACKOFF_FACTOR', 2.0)),
        'BACKOFF_MAX': int(os.environ.get('RATE_LIMIT_AUTH_BACKOFF_MAX', 300)),
    },
    'PUBLIC': {
        'MAX_REQUESTS': int(os.environ.get('RATE_LIMIT_PUBLIC_MAX', 120)),
        'WINDOW': int(os.environ.get('RATE_LIMIT_PUBLIC_WINDOW', 60)),
    },
    'AUTHENTICATED': {
        'MAX_REQUESTS': int(os.environ.get('RATE_LIMIT_AUTHED_MAX', 300)),
        'WINDOW': int(os.environ.get('RATE_LIMIT_AUTHED_WINDOW', 60)),
    },
}

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'sevenshadesapp.error_handling.drf_exception_handler',
}

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(name)s (%(filename)s:%(lineno)d): %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '%(asctime)s [%(levelname)s]: %(message)s',
            'datefmt': '%H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'sevenshades.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'error.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'sevenshadesapp': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}
