import { useCallback, useEffect, useRef, useState } from 'react';
import { Alert, Box, Button, Chip, Dialog, DialogContent, DialogTitle, Grid, LinearProgress, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TablePagination, TableRow, TextField, Typography } from '@mui/material';
import { Link } from 'react-router-dom';
import { getData, postData } from '../../services/FetchDjangoApiServices';
import useOrderEvents from '../../services/useOrderEvents';
const money = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value || 0);
const label = value => (value || '—').replaceAll('_',' ');
const dateText = value => new Date(value).toLocaleString('en-IN');
const orderStatuses=['AWAITING_TRIAL_PAYMENT','TRY_REQUESTED','ASSIGNED','OUT_FOR_TRIAL','TRIAL_IN_PROGRESS','TRIAL_COMPLETED','AWAITING_SELECTION_APPROVAL','SELECTION_SUBMITTED','PAYMENT_PENDING','DELIVERED','NO_PURCHASE','CANCELLED'];
const ticketStatuses=['Open','In Progress','Resolved','Closed'];
const priorities=['Low','Normal','High','Urgent'];
function useReport(endpoint, filters) {
 const [result,setResult]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false); const sequence=useRef(0);
 const query=new URLSearchParams(Object.entries(filters).filter(([,value])=>value!=='' )).toString();
 const load=useCallback(async()=>{const id=++sequence.current;setBusy(true);const response=await getData(endpoint+'?'+query);if(id!==sequence.current)return;setBusy(false);if(response.status){setResult(response);setError('');}else{setResult(null);setError(response.message||'Unable to load report.');}},[endpoint,query]);
 useEffect(()=>{load();const cleanupSequence=sequence.current;return()=>{sequence.current=cleanupSequence+1;};},[load]); useOrderEvents(load);
 return {result,error,busy,load};
}
export function Stats({items}) {return <Grid container spacing={2}>{items.map(([name,value,hint])=><Grid item xs={12} sm={6} lg={3} key={name}><Paper variant="outlined" sx={{p:2.5,borderRadius:3,height:'100%'}}><Typography variant="body2" color="text.secondary">{name}</Typography><Typography variant="h4" sx={{fontWeight:800,my:1}}>{value}</Typography><Typography variant="caption" color="text.secondary">{hint}</Typography></Paper></Grid>)}</Grid>;}
function Filters({value,onChange,tickets=false,datesOnly=false}) {
 const set=(key,next)=>onChange({...value,[key]:next,page:1});
 const select=(key,title,values)=><TextField select size="small" label={title} value={value[key]||''} onChange={e=>set(key,e.target.value)} sx={{minWidth:155}}><MenuItem value="">All</MenuItem>{values.map(item=><MenuItem value={item} key={item}>{label(item)}</MenuItem>)}</TextField>;
 return <Paper variant="outlined" sx={{p:2,borderRadius:3}}><Stack direction={{xs:'column',md:'row'}} useFlexGap flexWrap="wrap" gap={1.5}>
 {!datesOnly&&<TextField size="small" label={tickets?'Search customer or subject':'Search order, customer or city'} value={value.q||''} onChange={e=>set('q',e.target.value)} inputProps={{maxLength:120}} sx={{minWidth:240,flex:1}}/>}
 <TextField type="date" size="small" label="From date" InputLabelProps={{shrink:true}} value={value.from||''} onChange={e=>set('from',e.target.value)}/><TextField type="date" size="small" label="To date" InputLabelProps={{shrink:true}} value={value.to||''} onChange={e=>set('to',e.target.value)}/>
 {!datesOnly&&select('status','Status',tickets?ticketStatuses:orderStatuses)}{!datesOnly&&(tickets?select('priority','Priority',priorities):<>{select('payment','Final payment',['paid','pending'])}{select('mode','Payment method',['cash','razorpay','free','no_charge'])}</>)}
 <Button onClick={()=>onChange({page:1,page_size:20})}>Reset filters</Button></Stack></Paper>;
}
export function QuickDashboard(){
 const [filters,setFilters]=useState({});const {result,error,busy,load}=useReport('admin_quick_dashboard',filters);const data=result?.data;
 return <Stack spacing={3}><Stack direction="row" justifyContent="space-between"><Box><Typography variant="h4" fontWeight={800}>Quick Dashboard</Typography><Typography color="text.secondary">Your store at a glance. Order metrics use the selected booking dates (IST).</Typography></Box><Button onClick={load}>Refresh</Button></Stack><Filters datesOnly value={filters} onChange={setFilters}/>{busy&&<LinearProgress/>}{error&&<Alert severity="error">{error}</Alert>}{data&&<>
 <Stats items={[["Orders",data.orders,'Booked in selected period'],['Payments collected',money(data.collected),'Verified trial fees + settled balance'],['Completed trials',data.completed,'Delivered and no-purchase trials'],['Need assignment',data.unassigned,'Ready for dispatch']]}/>
 <Grid container spacing={2}><Grid item xs={12} md={7}><Paper variant="outlined" sx={{p:3,borderRadius:3}}><Typography variant="h6" fontWeight={700} mb={2}>Order progress</Typography>{Object.entries(data.statuses).length?Object.entries(data.statuses).map(([status,count])=><Box key={status} mb={2}><Stack direction="row" justifyContent="space-between"><Typography variant="body2">{label(status)}</Typography><Typography variant="body2">{count}</Typography></Stack><LinearProgress variant="determinate" value={count/Math.max(1,data.orders)*100} sx={{height:7,borderRadius:4,mt:1}}/></Box>):<Typography color="text.secondary">No orders in this period.</Typography>}</Paper></Grid>
 <Grid item xs={12} md={5}><Paper variant="outlined" sx={{p:3,borderRadius:3}}><Typography variant="h6" fontWeight={700}>Action centre</Typography><Typography variant="caption" color="text.secondary">Current store-wide availability and support queue</Typography>{[['Open tickets',data.open_tickets,'tickets'],['Low-stock variants (≤3)',data.low_stock,'displayproductdetails'],['Active riders',data.active_riders,'deliveryops'],['Awaiting approval (period)',data.awaiting_approval,'orders']].map(([title,count,to])=><Button key={title} component={Link} to={'/admindashboard/'+to} fullWidth sx={{justifyContent:'space-between',my:1,p:1.5,bgcolor:'#f4f6f5'}}>{title}<Chip label={count} size="small"/></Button>)}</Paper></Grid></Grid>
 <Paper variant="outlined" sx={{p:3,borderRadius:3}}><Stack direction="row" justifyContent="space-between"><Typography variant="h6" fontWeight={700}>Recent orders</Typography><Button component={Link} to="/admindashboard/sales">View report</Button></Stack>{data.recent.map(row=><Stack key={row.order_id} direction={{xs:'column',sm:'row'}} justifyContent="space-between" sx={{py:1.5,borderBottom:'1px solid #eee'}} gap={1}><Box><Typography fontWeight={600}>{row.order_id}</Typography><Typography variant="caption" color="text.secondary">{row.mobileno} · {dateText(row.created_at)}</Typography></Box><Chip label={label(row.status)} size="small"/></Stack>)}{!data.recent.length&&<Typography>No recent orders.</Typography>}</Paper></>}</Stack>;
}
export function SalesReport(){
 const [filters,setFilters]=useState({page:1,page_size:20});const {result,error,busy,load}=useReport('admin_sales_report',filters);const summary=result?.summary;
 return <Stack spacing={3}><Box><Typography variant="h4" fontWeight={800}>Sales Report</Typography><Typography color="text.secondary">Filter by order booking date (IST), customer, status or payment. Totals cover all matching orders.</Typography></Box><Filters value={filters} onChange={setFilters}/>{busy&&<LinearProgress/>}{error&&<Alert severity="error">{error}</Alert>}{summary&&<Stats items={[["Matching orders",summary.orders,'All filtered results'],['Collected',money(summary.collected),'Trial '+money(summary.trial_collected)+' + final '+money(summary.final_collected)],['Outstanding bills',money(summary.outstanding),'Generated, unpaid balances'],['Completed',summary.completed,'Delivered / no purchase']]}/>}
 <Paper variant="outlined" sx={{borderRadius:3,overflow:'hidden'}}><Stack direction="row" justifyContent="space-between" sx={{p:2}}><Typography variant="h6">Order sales ledger</Typography><Button onClick={load}>Refresh</Button></Stack><TableContainer><Table size="small"><TableHead><TableRow>{['Order / booked','Customer','Status','Final payment','Items value','Trial paid','Fee adjusted','Final paid','Total collected','Bill balance'].map(text=><TableCell key={text}>{text}</TableCell>)}</TableRow></TableHead><TableBody>{result?.data.map(row=><TableRow key={row.order_id} hover><TableCell>{row.order_id}<Typography variant="caption" display="block">{dateText(row.created_at)}</Typography></TableCell><TableCell><b>{row.customer.name}</b><Typography variant="caption" display="block">{row.customer.mobile}</Typography><Typography variant="caption" display="block">{row.customer.email}</Typography></TableCell><TableCell><Chip size="small" label={label(row.status)}/></TableCell><TableCell>{label(row.payment_status)}<Typography variant="caption" display="block">{row.payment_mode||'Not selected'}</Typography></TableCell>{['items_total','trial_collected','fee_adjusted','final_collected','collected','balance'].map(key=><TableCell key={key} sx={{whiteSpace:'nowrap'}}>{money(row[key])}</TableCell>)}</TableRow>)}{result&&!result.data.length&&<TableRow><TableCell colSpan={10} align="center" sx={{py:5}}>No orders match these filters.</TableCell></TableRow>}</TableBody></Table></TableContainer><TablePagination component="div" count={result?.total||0} page={(filters.page||1)-1} rowsPerPage={filters.page_size||20} rowsPerPageOptions={[10,20,50]} onPageChange={(_,p)=>setFilters({...filters,page:p+1})} onRowsPerPageChange={e=>setFilters({...filters,page:1,page_size:Number(e.target.value)})}/></Paper></Stack>;
}
export function SupportTickets(){
 const [filters,setFilters]=useState({page:1,page_size:20}),[selected,setSelected]=useState(null),[saving,setSaving]=useState(false),[message,setMessage]=useState('');const {result,error,busy,load}=useReport('admin_tickets',filters);
 const save=async()=>{setSaving(true);setMessage('');const result=await postData('admin_ticket_update',{id:selected.id,version:selected.version,status:selected.status,priority:selected.priority,response:selected.response});setSaving(false);if(result.status){setSelected(null);load();}else setMessage(result.message);};
 return <Stack spacing={3}><Box><Typography variant="h4" fontWeight={800}>Support Tickets</Typography><Typography color="text.secondary">Customer-raised requests, contact details and resolution status. Date filters use IST.</Typography></Box><Filters tickets value={filters} onChange={setFilters}/>{busy&&<LinearProgress/>}{error&&<Alert severity="error">{error}</Alert>}<Paper variant="outlined" sx={{borderRadius:3,overflow:'hidden'}}><Stack direction="row" justifyContent="space-between" sx={{p:2}}><Typography variant="h6">{result?.total||0} matching tickets</Typography><Button onClick={load}>Refresh</Button></Stack><TableContainer><Table><TableHead><TableRow>{['Ticket / raised','Customer','Subject','Priority','Status','Action'].map(text=><TableCell key={text}>{text}</TableCell>)}</TableRow></TableHead><TableBody>{result?.data.map(row=><TableRow key={row.id} hover><TableCell>{row.reference}<Typography variant="caption" display="block">{dateText(row.created_at)}</Typography></TableCell><TableCell><b>{row.customer.name}</b><Typography variant="body2">{row.customer.mobile}</Typography><Typography variant="caption">{row.customer.email}</Typography></TableCell><TableCell sx={{maxWidth:300,overflowWrap:'anywhere'}}>{row.subject}</TableCell><TableCell><Chip label={row.priority} color={['Urgent','High'].includes(row.priority)?'warning':'default'} size="small"/></TableCell><TableCell><Chip label={row.status} size="small" color={['Resolved','Closed'].includes(row.status)?'success':'info'}/></TableCell><TableCell><Button onClick={()=>{setSelected(row);setMessage('');}}>View / update</Button></TableCell></TableRow>)}{result&&!result.data.length&&<TableRow><TableCell colSpan={6} align="center" sx={{py:5}}>No tickets match these filters.</TableCell></TableRow>}</TableBody></Table></TableContainer><TablePagination component="div" count={result?.total||0} page={(filters.page||1)-1} rowsPerPage={filters.page_size||20} rowsPerPageOptions={[10,20,50]} onPageChange={(_,p)=>setFilters({...filters,page:p+1})} onRowsPerPageChange={e=>setFilters({...filters,page:1,page_size:Number(e.target.value)})}/></Paper>
 <Dialog open={!!selected} onClose={()=>!saving&&setSelected(null)} maxWidth="sm" fullWidth><DialogTitle>{selected?.reference} · Ticket details</DialogTitle><DialogContent>{selected&&<Stack spacing={2} sx={{pt:1}}>{message&&<Alert severity="error">{message}</Alert>}<Typography fontWeight={700}>{selected.customer.name} · {selected.customer.mobile}</Typography><Typography variant="body2">{selected.customer.email}</Typography><Typography variant="h6">{selected.subject}</Typography><Typography sx={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{selected.message}</Typography><TextField select label="Status" value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value})}>{ticketStatuses.map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField><TextField select label="Priority" value={selected.priority} onChange={e=>setSelected({...selected,priority:e.target.value})}>{priorities.map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField><TextField label="Customer-visible response" multiline minRows={3} value={selected.response} inputProps={{maxLength:2000}} helperText="This response appears in the customer's Help section." onChange={e=>setSelected({...selected,response:e.target.value})}/><Stack direction="row" gap={1}><Button disabled={saving} variant="contained" onClick={save}>Save update</Button><Button disabled={saving} onClick={()=>setSelected(null)}>Cancel</Button></Stack></Stack>}</DialogContent></Dialog></Stack>;
}
