import { useCallback, useEffect, useState } from 'react';
import { Alert, Button, Paper, Stack, TextField, Typography } from '@mui/material';
import { getData, postData } from '../../services/FetchDjangoApiServices';
import { CancelTrialButton } from '../../services/TrialInventoryControls';

export default function PaymentRecovery() {
 const [rows,setRows]=useState([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[q,setQ]=useState(''),[search,setSearch]=useState(''),[ids,setIds]=useState({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const load=useCallback(async()=>{const result=await getData('admin_payment_recovery?page='+page+'&q='+encodeURIComponent(search));if(result.status){setRows(result.data);setTotal(result.total);setError('');}else{setRows([]);setError(result.message);}},[page,search]);
 useEffect(()=>{load();},[load]);
 const act=async(endpoint,body)=>{if(busy)return;setBusy(true);setMessage('');const result=await postData(endpoint,body);setMessage(result.status?(endpoint==='admin_expire_reservations'?result.data.expired+' safe reservations released.':result.data.message||'Payment status: '+result.data.state):result.message);await load();setBusy(false);};
 return <Stack spacing={3}><Typography variant="h4" fontWeight={800}>Payment & reservation recovery</Typography><Alert severity="info">Only unpaid reservations with no online payment attempt expire automatically after 30 minutes. Payment attempts stay reserved until verified. This screen never marks a payment paid just because an ID was entered.</Alert><Stack direction="row" gap={1} flexWrap="wrap"><TextField label="Order or customer mobile" value={q} onChange={event=>setQ(event.target.value)}/><Button onClick={()=>{setPage(1);setSearch(q.trim());}}>Search</Button><Button onClick={load} disabled={busy}>Refresh</Button><Button disabled={busy} onClick={()=>act('admin_expire_reservations',{})}>Release safe expired reservations</Button></Stack>{error&&<Alert severity="error">{error}</Alert>}{message&&<Alert>{message}</Alert>}
 {rows.map(row=><Paper key={row.order_id} variant="outlined" sx={{p:2}}><Stack spacing={2}><Typography fontWeight={700}>{row.order_id} · {row.mobile}</Typography><Typography>{row.status.replaceAll('_',' ')} · Trial fee ₹{row.try_fee}</Typography>{row.expires_at&&<Typography>Reservation deadline: {new Date(row.expires_at).toLocaleString()}</Typography>}{row.can_cancel?<CancelTrialButton orderId={row.order_id} onCancelled={load}/>:<Typography color="text.secondary">{row.cancellation_blocker}</Typography>}{row.attempts.map(attempt=><Paper key={attempt.id} variant="outlined" sx={{p:2}}><Stack spacing={1}><Typography>Attempt #{attempt.id} · {attempt.purpose} · {attempt.state} · ₹{attempt.amount_paise/100}</Typography><Typography>Receipt reference: {attempt.receipt_reference||'Legacy attempt — match local_payment_id in provider notes'}</Typography><Typography>Provider order: {attempt.gateway_order_id||'Not recorded'}</Typography>{attempt.gateway_order_id?<Button disabled={busy} onClick={()=>act('admin_check_payment',{attempt_id:attempt.id})}>Check existing payment</Button>:<><TextField label={'Original Razorpay order ID for attempt '+attempt.id} value={ids[attempt.id]||''} onChange={event=>setIds({...ids,[attempt.id]:event.target.value})} helperText="Find the original order in Razorpay using the reference above. The server verifies its amount and identity."/><Button disabled={busy||!/^order_[A-Za-z0-9]+$/.test(ids[attempt.id]||'')} onClick={()=>act('admin_recover_payment',{attempt_id:attempt.id,gateway_order_id:ids[attempt.id]})}>Verify and recover original payment</Button></>}</Stack></Paper>)}</Stack></Paper>)}{!rows.length&&!error&&<Typography>No pending reservations or payments.</Typography>}<Stack direction="row" gap={2}><Button disabled={page===1||busy} onClick={()=>setPage(page-1)}>Previous</Button><Typography>Page {page} · {total} orders</Typography><Button disabled={page*20>=total||busy} onClick={()=>setPage(page+1)}>Next</Button></Stack></Stack>;
}
